# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

workspace 'WeatherAroundUs'

xcodeproj 'WeatherAroundUs'

pod 'Spring', '~> 1.0.1'
pod 'Alamofire', '~> 1.1'
pod "SwiftyJSON", ">= 2.1.3"
pod 'TMCache'
use_frameworks!

